#debug : true

spring:
  datasource:
    url: jdbc:mysql://58.213.112.90:7812/guizhou_upms_api?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: guizhou
    password: Hzyl2020
  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    host: smtp.qq.com
    username: 772977181@qq.com
    password: kyouvdvunledbcei
    protocol: smtp
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


# 打印sql
logging:
  path: /root/logs


pros:
  filesavepath: /root/images
  serverIp: http://61.243.10.48:901
# ca
caUrl:  https://58.42.231.108:5001
caUserName: SGGZY_YPCG

#银行测试url
bankUrl: http://222.85.178.210:8008/oba/gateway/v1/scs/SCS0111033/1.0.0

#银行基本信息
bank:
  bankName: 贵州银行
  bankCode: 110220
  serverUrl: http://222.85.178.210:8008/OAP/sit/gateway/v1/scs
  appId: "00870215"
  privateKey: 1ed316861ef661ac1186c6af9367d2f02ab40afbc64ac050e63514cebb9772a8
  fopPublicKey: 0432157a049d99758ec0ff362ef2e498fecb0921d2c72abf533959f6572f2f7e6081fd78dd90e480ff587acbcee9798bef5bd431790583e169ee11198827ba9f14
  superAccNo: "0136001900000041"
  superAccName: 测试客户0200099808810136001900000041

#是否必须使用ca登录
loginCa: false

#是否强制修改密码
checkEdiePass: false

#是否验证发票真伪
checkTbInvoiceYes: false

#是否验证发票真伪
checkAnswer: false








